api_key: ''
llm_model: ollama
base_url: https://d0b2f5d05cd4.ngrok-free.app
llm_model_name: gpt-oss:20b
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 600
proxies: {}
